export const SET_SELECTED_ITEM = "products.SET_SELECTED_ITEM";
export const SET_SELECTED_LOADING = "products.SET_SELECTED_LOADING";
export const SET_SELECTED_ERROR = "products.SET_SELECTED_ERROR";

export const SET_SELECTED_WAREHOUSES_FOR_DELETE = "products.SET_SELECTED_WAREHOUSES_FOR_DELETE";

export const SET_SELECTED_WAREHOUSES_ITEMS = "products.SET_SELECTED_WAREHOUSES_ITEMS";
export const SET_SELECTED_WAREHOUSES_ERROR = "products.SET_SELECTED_WAREHOUSES_ERROR";
export const SET_SELECTED_WAREHOUSES_LOADING = "products.SET_SELECTED_WAREHOUSES_LOADING";

export const SET_LIST_ITEMS = "products.SET_LIST_ITEMS";
export const SET_LIST_LOADING = "products.SET_LIST_LOADING";
export const SET_LIST_ERROR = "products.SET_LIST_ERROR";
export const SET_LIST_PAGE = "products.SET_LIST_PAGE";
export const SET_LIST_TOTAL_COUNT = "products.SET_LIST_TOTAL_COUNT";